#!/bin/bash

cppformat="{}"
cpplint="-whitespace/comments,-whitespace/indent"
phpmd="cleancode,codesize,controversial,design,naming,unusedcode"
tmppath="/tmp/precommit"

status=0
for changed in `git diff --staged --name-only`
do
  path=`git rev-parse --show-toplevel`/${changed}

  if [ -e ${path} ]; then
    basename=`basename ${changed}`
    extension=${basename##*.}

    case "${extension}" in
      "c"|"h"|"cpp"|"hpp" )
        colordiff -u ${path} <(clang-format -style="${cppformat}" ${path})
        clang-format -i -style="${cppformat}" ${path}
        if ! cpplint --filter=${cpplint} --quiet ${path}; then
          status=1
        fi;;
      
      "php" )
        cp ${path} ${tmppath}
        php-cs-fixer fix -q --using-cache no --diff --diff-format udiff ${path}
        colordiff -u ${tmppath} ${path}
        rm ${tmppath}
        if ! phpmd ${path} text ${phpmd}; then
          status=1
        fi;;

    esac

    git add ${path}
  fi
done

exit ${status}
