#!/bin/bash

cppformat="{}"
cpplint="-whitespace/comments,-whitespace/indent"

status=0
for changed in `git diff --staged --name-only`
do
  path=`git rev-parse --show-toplevel`/${changed}

  if [ -e ${path} ]; then
    basename=`basename ${changed}`
    extension=${basename##*.}

    case "${extension}" in
      "c"|"h"|"cpp"|"hpp" )
        colordiff -u ${path} <(clang-format -style="${cppformat}" ${path})
        clang-format -i -style="${cppformat}" ${path}
        if ! cpplint --filter=${cpplint} --quiet ${path}; then
          status=1
        fi;;
    esac

    git add ${path}
  fi
done

exit ${status}
